apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinicapp
  template:
    metadata:
      labels:
        app: petclinicapp
    spec:
      containers:
      - name: petclinicapppod
        image: pratikbhagat1/springapp:v1
        ports:
        - containerPort: 8080

