apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgrespod
        image: postgres:15.3
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: petclinic
          - name: POSTGRES_USER
            value: petclinic
          - name: POSTGRES_DB
            value: petclinic